[package]
name = "assembler6502"
version = "0.1.0"
authors = ["grant0417 <grantgurvis@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.0"